export interface LegalTagDefinition {
  tag: string;
  family: string;
  aliases: string[];
}

export const LEGAL_TAG_DEFINITIONS: LegalTagDefinition[] = [
  { tag: "syarat_sah_perjanjian", family: "contract_formation", aliases: ["syarat sah", "perjanjian sah", "kontrak sah", "pasal 1320"] },
  { tag: "kesepakatan", family: "contract_formation", aliases: ["sepakat", "setuju", "persetujuan", "dipaksa tanda tangan", "tidak sadar setuju"] },
  { tag: "kecakapan", family: "contract_formation", aliases: ["belum dewasa", "anak di bawah umur", "tidak cakap", "wali"] },
  { tag: "objek_tertentu", family: "contract_formation", aliases: ["objek tidak jelas", "barang tidak jelas", "jasa tidak jelas", "yang diperjanjikan tidak jelas"] },
  { tag: "sebab_halal", family: "contract_formation", aliases: ["melanggar hukum", "tujuan ilegal", "sebab terlarang", "perjanjian ilegal"] },
  { tag: "itikad_baik", family: "contract_formation", aliases: ["itikad baik", "tidak fair", "tidak jujur", "menjebak", "menipu"] },
  { tag: "wanprestasi", family: "contract_formation", aliases: ["ingkar janji", "tidak memenuhi janji", "wanprestasi", "gagal memenuhi kewajiban"] },
  { tag: "perbuatan_melawan_hukum", family: "contract_formation", aliases: ["melawan hukum", "merugikan", "perbuatan melawan hukum", "pmh"] },

  { tag: "perlindungan_konsumen", family: "consumer_protection", aliases: ["konsumen", "pelanggan", "pembeli", "penyewa", "pengguna layanan"] },
  { tag: "klausul_baku", family: "consumer_protection", aliases: ["klausul baku", "syarat sepihak", "tidak bisa dinegosiasi", "take it or leave it", "aturan sepihak"] },
  { tag: "pengalihan_tanggung_jawab", family: "consumer_protection", aliases: ["tanggung jawab dialihkan", "semua risiko saya", "tidak bertanggung jawab", "lepas tanggung jawab"] },
  { tag: "pembatasan_ganti_rugi", family: "consumer_protection", aliases: ["ganti rugi dibatasi", "kompensasi kecil", "tidak dapat ganti rugi", "maksimal penggantian"] },
  { tag: "larangan_pengembalian", family: "consumer_protection", aliases: ["tidak boleh retur", "barang tidak bisa dikembalikan", "no return", "pengembalian ditolak"] },
  { tag: "pembuktian_sepihak", family: "consumer_protection", aliases: ["bukti sepihak", "keputusan final sepihak", "catatan perusahaan yang berlaku", "menentukan sendiri"] },
  { tag: "perubahan_sepihak", family: "consumer_protection", aliases: ["ubah sepihak", "syarat bisa berubah", "harga bisa berubah", "ketentuan berubah sewaktu waktu"] },

  { tag: "denda", family: "payment_and_penalty", aliases: ["denda", "penalty", "penalti", "sanksi uang", "biaya hukuman"] },
  { tag: "bunga", family: "payment_and_penalty", aliases: ["bunga", "interest", "bunga harian", "bunga berjalan"] },
  { tag: "biaya_tersembunyi", family: "payment_and_penalty", aliases: ["biaya tersembunyi", "admin fee", "biaya admin", "biaya tambahan", "charge tambahan"] },
  { tag: "keterlambatan_pembayaran", family: "payment_and_penalty", aliases: ["telat bayar", "terlambat bayar", "nunggak", "jatuh tempo", "keterlambatan"] },
  { tag: "penagihan", family: "payment_and_penalty", aliases: ["ditagih", "debt collector", "kolektor", "penagihan kasar", "diteror"] },
  { tag: "refund", family: "payment_and_penalty", aliases: ["refund", "pengembalian dana", "uang kembali", "refund ditolak", "dana ditahan"] },
  { tag: "deposit", family: "payment_and_penalty", aliases: ["deposit", "uang jaminan", "jaminan ditahan", "security deposit"] },
  { tag: "pembayaran_berulang", family: "payment_and_penalty", aliases: ["langganan", "subscription", "tagihan bulanan", "perpanjang otomatis"] },
  { tag: "auto_debit", family: "payment_and_penalty", aliases: ["auto debit", "debet otomatis", "potong otomatis", "kartu ditagih"] },

  { tag: "pemutusan_sepihak", family: "termination_and_default", aliases: ["putus sepihak", "diputus sepihak", "mengakhiri sepihak", "kontrak dihentikan sepihak"] },
  { tag: "pembatalan", family: "termination_and_default", aliases: ["batal", "dibatalkan", "pembatalan", "cancel"] },
  { tag: "pengakhiran", family: "termination_and_default", aliases: ["pengakhiran", "berakhir", "terminasi", "termination"] },
  { tag: "cidera_janji", family: "termination_and_default", aliases: ["cidera janji", "cedera janji", "default", "breach"] },
  { tag: "masa_tenggang", family: "termination_and_default", aliases: ["masa tenggang", "grace period", "waktu perbaikan", "kesempatan memperbaiki"] },
  { tag: "somasi", family: "termination_and_default", aliases: ["somasi", "teguran", "surat peringatan", "peringatan tertulis"] },
  { tag: "akselerasi_pembayaran", family: "termination_and_default", aliases: ["langsung lunas", "semua cicilan jatuh tempo", "akselerasi", "pelunasan dipercepat"] },

  { tag: "pengalihan_risiko", family: "risk_allocation", aliases: ["risiko ditanggung saya", "semua risiko saya", "pengalihan risiko", "beban risiko"] },
  { tag: "indemnity", family: "risk_allocation", aliases: ["indemnity", "ganti rugi semua", "membebaskan dari tuntutan", "menanggung klaim"] },
  { tag: "hold_harmless", family: "risk_allocation", aliases: ["hold harmless", "tidak menuntut", "membebaskan tanggung jawab"] },
  { tag: "limitation_of_liability", family: "risk_allocation", aliases: ["batas tanggung jawab", "liability dibatasi", "tanggung jawab maksimal"] },
  { tag: "force_majeure", family: "risk_allocation", aliases: ["force majeure", "keadaan kahar", "bencana", "di luar kuasa", "wabah"] },
  { tag: "asuransi", family: "risk_allocation", aliases: ["asuransi", "pertanggungan", "klaim asuransi", "polis"] },
  { tag: "kerusakan_barang", family: "risk_allocation", aliases: ["barang rusak", "kerusakan", "hilang", "cacat barang"] },

  { tag: "sengketa", family: "dispute_resolution", aliases: ["sengketa", "perselisihan", "dispute", "masalah hukum"] },
  { tag: "arbitrase", family: "dispute_resolution", aliases: ["arbitrase", "bani", "arbitration", "arbiter"] },
  { tag: "mediasi", family: "dispute_resolution", aliases: ["mediasi", "mediator", "musyawarah", "negosiasi sengketa"] },
  { tag: "forum_hukum", family: "dispute_resolution", aliases: ["forum hukum", "pengadilan mana", "kompetensi pengadilan", "venue"] },
  { tag: "domisili_hukum", family: "dispute_resolution", aliases: ["domisili hukum", "kedudukan hukum", "alamat hukum"] },
  { tag: "choice_of_law", family: "dispute_resolution", aliases: ["hukum yang berlaku", "choice of law", "governing law", "hukum asing"] },
  { tag: "pengadilan", family: "dispute_resolution", aliases: ["pengadilan", "pn", "gugatan", "litigasi"] },
  { tag: "small_claim", family: "dispute_resolution", aliases: ["gugatan sederhana", "small claim", "nilai kecil"] },

  { tag: "data_pribadi", family: "privacy_and_data", aliases: ["data pribadi", "nik", "ktp", "privasi", "nomor hp", "foto ktp"] },
  { tag: "persetujuan_data", family: "privacy_and_data", aliases: ["izin data", "persetujuan data", "consent", "setuju data dipakai"] },
  { tag: "pemrosesan_data", family: "privacy_and_data", aliases: ["olah data", "pemrosesan data", "data dipakai", "profiling"] },
  { tag: "transfer_data", family: "privacy_and_data", aliases: ["data dibagikan", "transfer data", "pihak ketiga", "data dijual"] },
  { tag: "retensi_data", family: "privacy_and_data", aliases: ["data disimpan", "hapus data", "retensi", "berapa lama data"] },
  { tag: "kebocoran_data", family: "privacy_and_data", aliases: ["data bocor", "kebocoran", "diretas", "leak"] },
  { tag: "hak_subjek_data", family: "privacy_and_data", aliases: ["hak akses data", "hak hapus", "koreksi data", "tarik persetujuan"] },

  { tag: "akun", family: "digital_and_platform", aliases: ["akun", "account", "login", "profil"] },
  { tag: "suspensi_akun", family: "digital_and_platform", aliases: ["akun dibekukan", "akun ditutup", "suspend", "banned", "saldo ditahan"] },
  { tag: "moderasi_konten", family: "digital_and_platform", aliases: ["konten dihapus", "moderasi", "take down", "pelanggaran konten"] },
  { tag: "e_commerce", family: "digital_and_platform", aliases: ["ecommerce", "e-commerce", "marketplace", "toko online"] },
  { tag: "tanda_tangan_elektronik", family: "digital_and_platform", aliases: ["tanda tangan elektronik", "esign", "e-sign", "tte"] },
  { tag: "transaksi_elektronik", family: "digital_and_platform", aliases: ["transaksi elektronik", "online", "digital", "sistem elektronik"] },
  { tag: "akses_layanan", family: "digital_and_platform", aliases: ["akses layanan", "layanan tidak bisa dipakai", "downtime", "fitur dicabut"] },

  { tag: "hubungan_kerja", family: "employment_and_services", aliases: ["karyawan", "hubungan kerja", "pegawai", "phk"] },
  { tag: "kontraktor_independen", family: "employment_and_services", aliases: ["freelance", "kontraktor", "mitra", "bukan karyawan"] },
  { tag: "upah", family: "employment_and_services", aliases: ["upah", "gaji", "honor", "fee jasa"] },
  { tag: "lembur", family: "employment_and_services", aliases: ["lembur", "overtime", "jam kerja lebih"] },
  { tag: "non_compete", family: "employment_and_services", aliases: ["non compete", "tidak boleh kerja di pesaing", "larangan bersaing"] },
  { tag: "non_solicit", family: "employment_and_services", aliases: ["non solicit", "tidak boleh ajak klien", "tidak boleh rekrut"] },
  { tag: "kerahasiaan", family: "employment_and_services", aliases: ["rahasia", "nda", "confidential", "kerahasiaan"] },
  { tag: "hak_kekayaan_intelektual", family: "employment_and_services", aliases: ["hak cipta kerja", "ip milik perusahaan", "hasil kerja milik"] },

  { tag: "sewa", family: "property_and_rent", aliases: ["sewa", "kontrak rumah", "ruko", "apartemen", "kos"] },
  { tag: "deposit_sewa", family: "property_and_rent", aliases: ["deposit sewa", "uang jaminan sewa", "deposit kos"] },
  { tag: "pengosongan", family: "property_and_rent", aliases: ["pengosongan", "diusir", "keluar dari rumah", "vacate"] },
  { tag: "perawatan", family: "property_and_rent", aliases: ["perawatan", "maintenance", "perbaikan", "renovasi"] },
  { tag: "kerusakan_properti", family: "property_and_rent", aliases: ["kerusakan properti", "tembok rusak", "barang sewaan rusak"] },
  { tag: "kenaikan_sewa", family: "property_and_rent", aliases: ["sewa naik", "kenaikan sewa", "harga sewa berubah"] },

  { tag: "pinjaman", family: "financing_and_credit", aliases: ["pinjaman", "utang", "loan", "kredit"] },
  { tag: "jaminan_fidusia", family: "financing_and_credit", aliases: ["fidusia", "jaminan fidusia", "bpkb", "objek jaminan"] },
  { tag: "agunan", family: "financing_and_credit", aliases: ["agunan", "jaminan", "collateral", "sertifikat"] },
  { tag: "cicilan", family: "financing_and_credit", aliases: ["cicilan", "angsuran", "installment", "bayar bulanan"] },
  { tag: "restrukturisasi", family: "financing_and_credit", aliases: ["restrukturisasi", "keringanan", "reschedule", "renegosiasi utang"] },
  { tag: "kolektibilitas", family: "financing_and_credit", aliases: ["slik", "bi checking", "kolektibilitas", "skor kredit"] },
  { tag: "pinjol", family: "financing_and_credit", aliases: ["pinjol", "pinjaman online", "fintech lending", "galbay"] },
  { tag: "leasing", family: "financing_and_credit", aliases: ["leasing", "pembiayaan", "kredit motor", "kredit mobil"] },

  { tag: "perbankan", family: "financial_services", aliases: ["bank", "rekening", "perbankan", "tabungan"] },
  { tag: "ojk", family: "financial_services", aliases: ["ojk", "otoritas jasa keuangan", "regulator keuangan"] },
  { tag: "bi", family: "financial_services", aliases: ["bank indonesia", "bi", "qris", "sistem pembayaran"] },
  { tag: "asuransi_keuangan", family: "financial_services", aliases: ["asuransi jiwa", "asuransi kesehatan", "premi", "klaim ditolak"] },
  { tag: "paylater", family: "financial_services", aliases: ["paylater", "bayar nanti", "spaylater", "gopaylater"] },
  { tag: "investasi", family: "financial_services", aliases: ["investasi", "return", "profit", "modal", "robot trading"] },
  { tag: "anti_pencucian_uang", family: "financial_services", aliases: ["aml", "pencucian uang", "kyc", "sumber dana"] },

  { tag: "jual_beli", family: "corporate_and_commercial", aliases: ["jual beli", "pembelian", "penjualan", "purchase"] },
  { tag: "distribusi", family: "corporate_and_commercial", aliases: ["distributor", "distribusi", "reseller", "stokis"] },
  { tag: "agen", family: "corporate_and_commercial", aliases: ["agen", "agency", "perwakilan"] },
  { tag: "franchise", family: "corporate_and_commercial", aliases: ["franchise", "waralaba", "franchisor", "franchisee"] },
  { tag: "saham", family: "corporate_and_commercial", aliases: ["saham", "shareholder", "pemegang saham", "equity"] },
  { tag: "direksi", family: "corporate_and_commercial", aliases: ["direksi", "direktur", "pengurus perusahaan"] },
  { tag: "komisaris", family: "corporate_and_commercial", aliases: ["komisaris", "dewan komisaris", "pengawas"] },
  { tag: "kuasa", family: "corporate_and_commercial", aliases: ["kuasa", "surat kuasa", "power of attorney", "wakil"] },
  { tag: "perizinan_usaha", family: "corporate_and_commercial", aliases: ["izin usaha", "nib", "oss", "perizinan usaha"] },

  { tag: "hak_cipta", family: "intellectual_property", aliases: ["hak cipta", "copyright", "ciptaan", "konten saya"] },
  { tag: "merek", family: "intellectual_property", aliases: ["merek", "brand", "trademark", "nama dagang"] },
  { tag: "paten", family: "intellectual_property", aliases: ["paten", "invensi", "patent"] },
  { tag: "lisensi", family: "intellectual_property", aliases: ["lisensi", "license", "izin pakai", "hak pakai"] },
  { tag: "royalti", family: "intellectual_property", aliases: ["royalti", "royalty", "bagi hasil ip"] },
  { tag: "pengalihan_hak", family: "intellectual_property", aliases: ["hak dialihkan", "assignment", "alih hak", "milik sepenuhnya"] },
  { tag: "software", family: "intellectual_property", aliases: ["software", "aplikasi", "source code", "kode sumber"] },

  { tag: "perizinan", family: "public_law_and_compliance", aliases: ["izin", "lisensi usaha", "izin pemerintah", "persetujuan regulator"] },
  { tag: "sanksi_administratif", family: "public_law_and_compliance", aliases: ["sanksi administratif", "denda administratif", "teguran regulator"] },
  { tag: "pidana", family: "public_law_and_compliance", aliases: ["pidana", "penjara", "lapor polisi", "tindak pidana"] },
  { tag: "pajak", family: "public_law_and_compliance", aliases: ["pajak", "ppn", "pph", "npwp", "faktur"] },
  { tag: "kepatuhan", family: "public_law_and_compliance", aliases: ["compliance", "kepatuhan", "wajib patuh", "aturan regulator"] },
  { tag: "pelaporan", family: "public_law_and_compliance", aliases: ["lapor", "pelaporan", "laporan berkala", "notifikasi regulator"] },
  { tag: "larangan", family: "public_law_and_compliance", aliases: ["dilarang", "larangan", "tidak boleh", "prohibited"] },
  { tag: "kewajiban_regulator", family: "public_law_and_compliance", aliases: ["wajib", "kewajiban regulator", "harus memenuhi", "mandatory"] },

  { tag: "alat_bukti", family: "evidence_and_procedure", aliases: ["bukti", "alat bukti", "evidence", "rekaman", "chat"] },
  { tag: "dokumen_elektronik", family: "evidence_and_procedure", aliases: ["dokumen elektronik", "email", "screenshot", "whatsapp"] },
  { tag: "tanda_tangan", family: "evidence_and_procedure", aliases: ["tanda tangan", "ttd", "ditandatangani", "signature"] },
  { tag: "notaris", family: "evidence_and_procedure", aliases: ["notaris", "akta", "waarmerking", "legalisasi"] },
  { tag: "legalisasi", family: "evidence_and_procedure", aliases: ["legalisasi", "apostille", "pengesahan", "dilegalisir"] },
  { tag: "pembuktian", family: "evidence_and_procedure", aliases: ["membuktikan", "beban pembuktian", "siapa yang harus bukti"] },
  { tag: "surat_kuasa", family: "evidence_and_procedure", aliases: ["surat kuasa", "kuasa khusus", "wakil hukum"] },
];
